---
default:
  threads: 40
  producer_type: BaseProducer
  producer_config:
    bootstrap.servers: localhost:9092

scenarios:
  qinyujia:
    repeat_times: 50
    repeat_pause: 0
    topic: images
    message_size: 500000
    message_count: 5000
